#page title
page_title                                : fastbackward                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1537751066                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id1537751066                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : fastbackward                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Relive your forgotten photos from your camera roll on a daily basis.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Maximilian Krauß                               
your_link                                 : https://max.krauss.io                  
your_city                                 : Berlin                                
email_address                             : max@krauss.io
facebook_username                         :                                           
instagram_username                        : der_instamax
twitter_username                          : DonnieBerlin
github_username                           : maximilian-krauss
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Relive forgotten memories
    description                           : fastbackward shows you all photos you took on this day throughout the past years. For more than one year of memories you'll need the pro version of fastbackward.
    fontawesome_icon_name                 : images
    
  - title                                 : iCloud Support
    description                           : Works fine with photos stored inside Apple iCloud.
    fontawesome_icon_name                 : cloud

  - title                                 : Notifications
    description                           : Open fastbackward only when you need to. With the built-in notification feature you can get notified on each day you have memories.
    fontawesome_icon_name                 : info-circle

  - title                                 : Extended metadata (Pro)
    description                           : View extended metadata for each photo like location, camera model/make and much more.
    fontawesome_icon_name                 : file-image

  - title                                 : Secure by default
    description                           : None of your photos or even it's metadata will ever leave your iPhone.
    fontawesome_icon_name                 : lock
  
  - title                                 : Delete memories
    description                           : Found a screenshot you took accidental five years ago? Those things you can delete with one tap.
    fontawesome_icon_name                 : trash-alt

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/_headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#424242"
cover_overlay_transparency                : 0.4

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FF551F"

app_title_color                           : "#FF551F"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FF551F"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
